In [ ]:
import numpy as np

In [ ]:
 arr = np.arange(10)

In [ ]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
 arr2 = np.zeros((3,2), dtype = 'int32')

In [ ]:
print(arr2)

[[0 0]
 [0 0]
 [0 0]]


In [ ]:
arr3 = np.ones((3,2))

In [ ]:
print(arr3)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
arr4 = [0,1,2,3,4,5,6,7,8,9]
sequence_array = np.arange(10)
print(sequence_array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(sequence_array.dtype, sequence_array.shape)

int64 (10,)


In [ ]:
 zero_array = np.zeros((3,2), dtype = 'int32')

In [ ]:
print(zero_array)

[[0 0]
 [0 0]
 [0 0]]


In [ ]:
one_array = np.ones((3,2), dtype = 'int32')
print(one_array)

[[1 1]
 [1 1]
 [1 1]]


In [ ]:
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
array2 = array1.reshape(2,5)
print(array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
array3 = array1.reshape(-1, 5)
print(array3)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
array4 = array1.reshape(5,2)
print(array4)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
array5 = array4.reshape(-1, 1)
print(array5)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
new_arr = np.ones(10)

In [ ]:
print(new_arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
sliced =new_arr[0:2]
print(sliced)

[1. 1.]


In [ ]:
  array1 = np.arange(start = 1, stop = 10)
  print(array1)

[1 2 3 4 5 6 7 8 9]


In [ ]:
value = array1[2]
print(value)

3


In [ ]:
value_last = array1[-1]
print(value_last)

9


In [ ]:
array2d = array1.reshape(3,3)

In [ ]:
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(array2d[2][2])

9


In [ ]:
array3 = array1[0:3]
print(array3)

[1 2 3]


In [ ]:
print(array1)
array4 = array1[-4:-1]

[1 2 3 4 5 6 7 8 9]


In [ ]:
print(array4)

[6 7 8]


In [ ]:
array4 = array1[:4]
print(array4)

[1 2 3 4]


In [ ]:
array2d = array1.reshape(3,3)
array5 - array2d[[2,]]

array([[-7, -8, -9],
       [-6, -7, -8],
       [-5, -6, -7],
       [-4, -5, -6],
       [-3, -4, -5],
       [-2, -3, -4],
       [-1, -2, -3],
       [ 0, -1, -2],
       [ 1,  0, -1],
       [ 2,  1,  0]])

In [ ]:
array = [1,5,4,2,3]
arrayx = np.sort([1,5,4,2,3])
sortedx = np.sort(array)
print(sortedx)

[1 2 3 4 5]
