In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [5]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [6]:
print(iris.data[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [7]:
print(iris.target)        #0,1,2가 각각 꽃이름들과 매칭 된다.

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [8]:
X = iris.data
y = iris.target 
# X가 iris data, y가 target data, 꽃 종ㅇ류


In [9]:
df = pd.DataFrame(X, columns = ['sepal_witdh(cm)', 'sepal_length(cm)', 'petal_width(cm)', 'petal_length(cm)'])    
#4개를 데이터 프레임으로 묶음

In [10]:
df.head()

sepal_witdh(cm)  sepal_length(cm)  petal_width(cm)  petal_length(cm)
0              5.1               3.5              1.4               0.2
1              4.9               3.0              1.4               0.2
2              4.7               3.2              1.3               0.2
3              4.6               3.1              1.5               0.2
4              5.0               3.6              1.4               0.2

In [ ]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['species'] = np.array([iris.target_names[i] for i in iris.target])

sns.pairplot(df, hue='species')
#seaborn 으로 그래프 시각화 , hue = 'species' -> 이 species 를 기준을 ㅗ분류하겠다
#3차원 이상 데이터 에서 주로 사용
#hue = 'species'->카테고리형 데이터가 섞여 있을 때 이걸로 카테고리 값에 따라 색상을 달리함


In [ ]:
 from sklearn.model_selection import train_test_split     #data나누는 거
 

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)
#70프로는 training data

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
log_r = LogisticRegression()

In [ ]:
log_r.fit(X,y)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [ ]:
W, b = log_r.coef_, log_r.intercept_

In [ ]:
W ,b

(array([[-0.41878528,  0.96703041, -2.5209973 , -1.08417682],
        [ 0.53124457, -0.31475282, -0.20008433, -0.94861142],
        [-0.1124593 , -0.65227759,  2.72108162,  2.03278825]]),
 array([  9.84037025,   2.21700109, -12.05737134]))

In [ ]:
print(log_r.score(X_train, y_train))

0.9619047619047619


In [ ]:
#X,y 둘다 train 데이터로 훈련시켰을 때의 값

In [ ]:
#이제 테스트 데이터로 실제  적용

In [ ]:
print(log_r.score(X_test, y_test))

1.0
